name: Mondoo Terraform scan
on: push
#     paths:
#       - "terraform-config/main.tf"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mondoohq/actions/terraform-hcl@v1.0.0
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}

