name: Terraform apply

on:
  workflow_dispatch:
    inputs:
      tf_apply:
        type: boolean

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply -auto-approve
